### ISSUE TITLE
Floating format box

### ISSUE THREAD

**Issue by theishshah** [tsl143/board#5] opened 2017-11-20 17:55 UTC
Not necessarily an issue, but the option to fix the format box to a corner as opposed to floating would be awesome, sometimes it can be obtrusive when writing on multiple lines/when I want to read and write at the same time

**Comment by tsl143** [comment] 2017-11-23 04:50
Thanks for feedback :)
Closing as duplicate of #1

**Closed as completed by tsl143** 2017-11-23 04:50 UTC
